@startuml class_scheme

!theme plain

class Telegram_server{
    + Update
}

class Server{
  + dispatcher : Dispatcher
  + start_polling(bot : Bot) : void
  + include_router(router : Router) : void
}
class Router{
  + cmd_start(message: Message, state: FSMContext) : void
  + cmd_start(message: Message) : void
  + start_quiz_handler(callback: CallbackQuery, state: FSMContext) : void
  + question_handler(callback: CallbackQuery, state: FSMContext) : void
  + explanation_handler(callback: CallbackQuery, state: FSMContext) : void
  + final_handler(callback: CallbackQuery, state: FSMContext) : void
}
class Quiz {
  + id: int
  + title: string
  - questions: List<Question>
  - countQuestions : int
  - startMsg
  - finalMsg
  + Quiz()
  + create_explanation_msg(curretQuestion : int, answer : string) : Dict[str, Any]
  + create_question_msg(curretQuestion : int) : Dict[str, Any]
  + get_start_message() : Dict[str, Any]
  + get_final_message(countTrueAns : int) : Dict[str, Any]
}

class Question{
  + text_question : string
  + text_explanation : string
  + true_answer : int
  - option : List<string>
  - media_question : string
  - media_explanation : string
  + Question(dict[string : Any])
  + get_media_question() : FSInputFile
  + get_media_explanation() : FSInputFile
  + get_option_keyboard() : InlineKeyboardMarkup
  + is_true_answer(answer : int) : bool
}

Quiz *-- Question
Router ..> Server
Router ..> Quiz
Server -- Telegram_server
@enduml